name: CI CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: AI Failure Prediction
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python predict_failure.py

      

      - name: Measure Build Time
        run: |
          start=$(date +%s)
          python model.py
          end=$(date +%s)
          build_time=$((end-start))
          echo "BUILD_TIME=$build_time" >> $GITHUB_ENV
          echo "Build Time: $build_time seconds"

      - name: Detect Build Time Anomaly
        continue-on-error: true

        run: python detect_build_time.py

      - name: Run Tests
        id: tests
        run: |
          python test.py || echo "TEST_FAILED=true" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t cicd-anomaly .

      - name: LLM Self Healing
        if: env.TEST_FAILED == 'true'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python self_healing/llm_agent.py
          echo "Self-healing triggered successfully. Exiting with success code."
          exit 0